# Generated by Django 5.2.9 on 2025-12-17 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('pdv', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('start_shift', 'Début de tournée'), ('arrival_pdv', 'Arrivée PDV')], default='start_shift', max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drivers.driver')),
                ('pdv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdv.pointdevente')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('synced', 'Synced'), ('paid_partial', 'Paid partial'), ('paid_full', 'Paid full')], default='recorded', max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drivers.driver')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drivers.driver')),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdv.pointdevente')),
            ],
        ),
    ]
