# Generated by Django 5.2.9 on 2025-12-25 21:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driveravailability_battery_level_and_more'),
        ('logistics', '0002_alter_collection_options_collection_created_by_and_more'),
        ('pdv', '0002_pdvsale_pdvstock_alter_pointdevente_options_and_more'),
        ('qr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ('-delivered_at',)},
        ),
        migrations.AddField(
            model_name='delivery',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdv_deliveries_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='qr_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='qr.qrscan'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivered_at'], name='logistics_d_deliver_2e3d05_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['pdv'], name='logistics_d_pdv_id_0b48cd_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['driver'], name='logistics_d_driver__8e6ade_idx'),
        ),
    ]
