# Generated by Django 5.2.9 on 2025-12-23 18:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('last_location_update', models.DateTimeField(blank=True, null=True, verbose_name='Dernière mise à jour de localisation')),
                ('current_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vitesse actuelle (km/h)')),
                ('battery_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Niveau de batterie (%)')),
                ('odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kilométrage')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Prochaine maintenance')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disponibilité chauffeur',
                'verbose_name_plural': 'Disponibilités chauffeurs',
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('license', 'Permis de conduire'), ('insurance', 'Assurance'), ('vehicle_registration', 'Carte grise'), ('identity', "Pièce d'identité"), ('contract', 'Contrat de travail'), ('medical', 'Certificat médical'), ('other', 'Autre')], max_length=30, verbose_name='Type de document')),
                ('file', models.FileField(blank=True, null=True, upload_to='driver_documents/%Y/%m/%d/', verbose_name='Fichier')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du fichier')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Document chauffeur',
                'verbose_name_plural': 'Documents chauffeurs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Début de période')),
                ('period_end', models.DateField(verbose_name='Fin de période')),
                ('collections_count', models.IntegerField(default=0, verbose_name='Nombre de collectes')),
                ('collections_volume', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volume collecté (L)')),
                ('deliveries_count', models.IntegerField(default=0, verbose_name='Nombre de livraisons')),
                ('deliveries_volume', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volume livré (L)')),
                ('distance_traveled', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distance parcourue (km)')),
                ('fuel_consumption', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Consommation carburant (L)')),
                ('earnings', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gains')),
                ('commission', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Commission')),
                ('rating', models.DecimalField(decimal_places=1, default='0.0', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('incidents', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Incidents')),
                ('complaints', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Réclamations')),
                ('efficiency_score', models.DecimalField(decimal_places=2, default='0.00', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Score d'efficacité")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Performance chauffeur',
                'verbose_name_plural': 'Performances chauffeurs',
                'ordering': ['-period_end'],
            },
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chauffeur', 'verbose_name_plural': 'Chauffeurs'},
        ),
        migrations.AddField(
            model_name='driver',
            name='assigned_zone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zone assignée'),
        ),
        migrations.AddField(
            model_name='driver',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salaire de base'),
        ),
        migrations.AddField(
            model_name='driver',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de commission (%)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Code unique du chauffeur (format: CH_ANNEE_HEX)', max_length=20, unique=True, verbose_name='Code chauffeur'),
        ),
        migrations.AddField(
            model_name='driver',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name="Date d'embauche"),
        ),
        migrations.AddField(
            model_name='driver',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration de l'assurance"),
        ),
        migrations.AddField(
            model_name='driver',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'assurance"),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Vérifié'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration du permis"),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de permis'),
        ),
        migrations.AddField(
            model_name='driver',
            name='max_capacity',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacité maximale (litres)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('on_duty', 'En service'), ('off_duty', 'Hors service'), ('on_break', 'En pause'), ('on_leave', 'En congé')], db_index=True, default='active', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='driver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_registration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Immatriculation'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type de véhicule'),
        ),
        migrations.AddField(
            model_name='driver',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='can_be_pdv',
            field=models.BooleanField(default=False, help_text='Peut servir comme point de vente', verbose_name='Peut être PDV'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='transport_mode',
            field=models.CharField(choices=[('vehicule', 'Véhicule'), ('velo', 'Vélo'), ('pied', 'À pied'), ('moto', 'Moto'), ('camion', 'Camion')], default='vehicule', max_length=20, verbose_name='Mode de transport'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['driver_code'], name='drivers_dri_driver__0f4e25_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['status'], name='drivers_dri_status_d7a5f5_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['transport_mode'], name='drivers_dri_transpo_2c55e9_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_verified'], name='drivers_dri_is_veri_98c4c3_idx'),
        ),
        migrations.AddField(
            model_name='driveravailability',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_driver_documents', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
        migrations.AddField(
            model_name='driverperformance',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='drivers.driver'),
        ),
        migrations.AddIndex(
            model_name='driverdocument',
            index=models.Index(fields=['document_type'], name='drivers_dri_documen_b2be8b_idx'),
        ),
        migrations.AddIndex(
            model_name='driverdocument',
            index=models.Index(fields=['is_verified'], name='drivers_dri_is_veri_632ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='driverdocument',
            index=models.Index(fields=['expiry_date'], name='drivers_dri_expiry__da8901_idx'),
        ),
        migrations.AddIndex(
            model_name='driverperformance',
            index=models.Index(fields=['period_start', 'period_end'], name='drivers_dri_period__0bf8f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='driverperformance',
            constraint=models.UniqueConstraint(fields=('driver', 'period_start', 'period_end'), name='uniq_driver_period'),
        ),
    ]
