# Generated by Django 5.2.9 on 2025-12-25 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driveravailability_driverdocument_driverperformance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveravailability',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Batterie (%)'),
        ),
        migrations.AlterField(
            model_name='driveravailability',
            name='current_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vitesse (km/h)'),
        ),
        migrations.AlterField(
            model_name='driveravailability',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière mise à jour localisation'),
        ),
    ]
