# Generated by Django 5.2.9 on 2025-12-25 21:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDVSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters_sold', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-sold_at'],
            },
        ),
        migrations.CreateModel(
            name='PDVStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_liters', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock PDV',
                'verbose_name_plural': 'Stocks PDV',
            },
        ),
        migrations.AlterModelOptions(
            name='pointdevente',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='pointdevente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointdevente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='pointdevente',
            index=models.Index(fields=['province', 'commune'], name='pdv_pointde_provinc_f04010_idx'),
        ),
        migrations.AddIndex(
            model_name='pointdevente',
            index=models.Index(fields=['name'], name='pdv_pointde_name_9680ec_idx'),
        ),
        migrations.AddField(
            model_name='pdvsale',
            name='pdv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='pdv.pointdevente'),
        ),
        migrations.AddField(
            model_name='pdvsale',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdv_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdvstock',
            name='pdv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='pdv.pointdevente'),
        ),
        migrations.AddIndex(
            model_name='pdvsale',
            index=models.Index(fields=['sold_at'], name='pdv_pdvsale_sold_at_e9198d_idx'),
        ),
        migrations.AddIndex(
            model_name='pdvsale',
            index=models.Index(fields=['pdv'], name='pdv_pdvsale_pdv_id_a9d8a5_idx'),
        ),
    ]
