# Generated by Django 5.2.9 on 2025-12-25 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_pdvsale_pdvstock_alter_pointdevente_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointdevente',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, unique=True),
        ),
        migrations.AddIndex(
            model_name='pointdevente',
            index=models.Index(fields=['code'], name='pdv_pointde_code_d1c422_idx'),
        ),
    ]
