# Generated by Django 5.2.9 on 2025-12-17 23:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('account_type', models.CharField(choices=[('client', 'Client'), ('fournisseur', 'Fournisseur'), ('commercant', 'Commerçant/Boutique'), ('livreur', 'Livreur'), ('partenaire', 'Partenaire'), ('entreprise', 'Entreprise')], db_index=True, default='client', max_length=20, verbose_name='Type de compte')),
                ('client_type', models.CharField(blank=True, choices=[('individuel', 'Individuel'), ('famille', 'Famille')], max_length=20, null=True, verbose_name='Type de client')),
                ('supplier_type', models.CharField(blank=True, choices=[('individuel', 'Individuel'), ('entreprise', 'Entreprise')], max_length=20, null=True, verbose_name='Type de fournisseur')),
                ('delivery_type', models.CharField(blank=True, choices=[('individuel', 'Individuel'), ('entreprise', 'Entreprise'), ('boutique', 'Boutique')], max_length=20, null=True, verbose_name='Type de livreur')),
                ('merchant_type', models.CharField(blank=True, choices=[('boutique', 'Boutique')], default='boutique', max_length=20, null=True, verbose_name='Type de commerçant')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('fournisseur', 'Fournisseur'), ('livreur', 'Livreur'), ('commercant', 'Commerçant'), ('partenaire', 'Partenaire'), ('agent', 'Agent'), ('client', 'Client')], db_index=True, default='client', max_length=20, verbose_name='Rôle')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nom complet')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Téléphone')),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code QR')),
                ('kyc_status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté'), ('exempted', 'Exempté')], db_index=True, default='pending', max_length=20)),
                ('account_status', models.CharField(choices=[('active', 'Actif'), ('pending_kyc', 'En attente KYC'), ('suspended', 'Suspendu'), ('deactivated', 'Désactivé')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journaux d'activité",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='user_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Document utilisateur',
                'verbose_name_plural': 'Documents utilisateur',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
