# Generated by Django 5.2.9 on 2025-12-19 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accepted_contract',
            field=models.BooleanField(default=False, verbose_name='Contrat accepté'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='accepted_terms',
            field=models.BooleanField(default=False, verbose_name='Conditions générales acceptées'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='boutique_services',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Services proposés'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='boutique_type',
            field=models.CharField(blank=True, choices=[('grocery', 'Épicerie'), ('electronics', 'Électronique'), ('clothing', 'Vêtements'), ('restaurant', 'Restaurant'), ('pharmacy', 'Pharmacie'), ('other', 'Autre')], max_length=20, null=True, verbose_name='Type de boutique'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_doc_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration des documents"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_entity_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individuel'), ('company', 'Société'), ('cooperative', 'Coopérative'), ('association', 'Association'), ('other', 'Autre')], max_length=20, null=True, verbose_name="Type d'entité commerciale"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name="Numéro d'immatriculation"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_tax_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro fiscal'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='colline_or_quartier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Colline/Quartier'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='delivery_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Instructions de livraison'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='delivery_vehicle',
            field=models.CharField(blank=True, choices=[('motorcycle', 'Moto'), ('bicycle', 'Vélo'), ('car', 'Voiture'), ('truck', 'Camion'), ('walking', 'À pied')], max_length=20, null=True, verbose_name='Véhicule de livraison'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom du contact d'urgence"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Téléphone du contact d'urgence"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relation avec le contact'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Masculin'), ('female', 'Féminin'), ('other', 'Autre')], max_length=10, null=True, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_document_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du document'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'émission"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_no_expiry',
            field=models.BooleanField(default=False, verbose_name="Pas de date d'expiration"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de pièce'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_type',
            field=models.CharField(blank=True, choices=[('cni', "Carte Nationale d'Identité"), ('passport', 'Passeport'), ('driving_license', 'Permis de conduire'), ('residence_card', 'Carte de résidence'), ('other', 'Autre')], max_length=20, null=True, verbose_name="Type de pièce d'identité"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification KYC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lumicash_msisdn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro Lumicash'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/%Y/%m/%d/', verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_delivery_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horaire de livraison préféré'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='user_signatures/%Y/%m/%d/', verbose_name='Signature'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vehicle_registration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Immatriculation du véhicule'),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du fichier'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='file_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Taille du fichier (KB)'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='verification_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes de vérification'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Vérifié'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('active', 'Actif'), ('pending_kyc', 'En attente KYC'), ('suspended', 'Suspendu'), ('deactivated', 'Désactivé')], db_index=True, default='active', max_length=20, verbose_name='Statut du compte'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté'), ('exempted', 'Exempté')], db_index=True, default='pending', max_length=20, verbose_name='Statut KYC'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(max_length=100, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='details',
            field=models.JSONField(default=dict, verbose_name='Détails'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='document_type',
            field=models.CharField(choices=[('id_card', "Carte d'identité"), ('passport', 'Passeport'), ('driving_license', 'Permis de conduire'), ('business_registration', "Certificat d'immatriculation"), ('tax_certificate', 'Certificat fiscal'), ('trade_license', 'Permis de commerce'), ('proof_of_address', 'Justificatif de domicile'), ('other', 'Autre')], max_length=50, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='file',
            field=models.FileField(upload_to='user_documents/%Y/%m/%d/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de téléchargement'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['account_type', 'role'], name='accounts_cu_account_f4a624_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['kyc_status'], name='accounts_cu_kyc_sta_9cf458_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['account_status'], name='accounts_cu_account_eb20fc_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone'], name='accounts_cu_phone_c30b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
    ]
