# Generated by Django 5.2.9 on 2025-12-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_accepted_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='boutique_type',
            field=models.CharField(blank=True, choices=[('boutique', 'Boutique'), ('restaurant', 'Restaurant'), ('supermarche', 'Supermarché')], max_length=20, null=True, verbose_name='Type de boutique'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='document_type',
            field=models.CharField(choices=[('id_card', "Carte d'identité"), ('passport', 'Passeport'), ('driving_license', 'Permis de conduire'), ('business_registration', "Certificat d'immatriculation"), ('tax_certificate', 'Certificat fiscal'), ('trade_license', 'Permis de commerce'), ('proof_of_address', 'Justificatif de domicile'), ('contract', 'Contrat'), ('other', 'Autre')], max_length=50, verbose_name='Type de document'),
        ),
    ]
