# Generated by Django 5.2.9 on 2025-12-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_boutique_type_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agent_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='Matricule Agent'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['agent_code'], name='accounts_cu_agent_c_e6e7f5_idx'),
        ),
    ]
