# ========================= apps/wallet/migrations/0001_initial.py =========================
# Generated by Django 5.2.9 on 2025-12-26 21:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(db_index=True, max_length=30, unique=True)),
                ("balance", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18)),
                ("currency", models.CharField(default="BIF", max_length=10)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tx_type",
                    models.CharField(
                        choices=[("credit", "Crédit"), ("debit", "Débit"), ("adjust", "Ajustement")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reference", models.CharField(blank=True, default="", max_length=140)),
                (
                    "provider",
                    models.CharField(
                        choices=[("internal", "Internal"), ("lumicash", "Lumicash")],
                        db_index=True,
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("provider_tx_id", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("success", "Success"), ("failed", "Failed")],
                        db_index=True,
                        default="success",
                        max_length=20,
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["address"], name="wallet_wall_address_c7bf63_idx"),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["is_active"], name="wallet_wall_is_acti_632cdc_idx"),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(fields=["tx_type", "created_at"], name="wallet_wall_tx_type_69d352_idx"),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(fields=["provider", "provider_tx_id"], name="wallet_wall_provide_55b0bf_idx"),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(fields=["status"], name="wallet_wall_status_66d39d_idx"),
        ),
    ]
