# ========================= apps/wallet/migrations/0002_create_wallettransaction_table_if_missing.py =========================
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=r"""
            -- If the DB is inconsistent (0001 marked applied but table missing),
            -- ensure wallet_wallettransaction exists before ALTER operations.

            CREATE TABLE IF NOT EXISTS wallet_wallettransaction (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                wallet_id bigint NOT NULL
                    REFERENCES wallet_wallet(id)
                    DEFERRABLE INITIALLY DEFERRED,

                tx_type varchar(20) NOT NULL,
                status varchar(20) NOT NULL DEFAULT 'success',
                amount numeric(18,2) NOT NULL,

                reference varchar(140) NOT NULL DEFAULT '',
                meta jsonb NOT NULL DEFAULT '{}'::jsonb,

                provider varchar(30) NOT NULL DEFAULT 'internal',
                provider_tx_id varchar(120) NOT NULL DEFAULT '',

                created_at timestamptz NOT NULL DEFAULT NOW()
            );

            -- indexes used in 0001
            CREATE INDEX IF NOT EXISTS wallet_wall_tx_type_69d352_idx
                ON wallet_wallettransaction(tx_type, created_at);

            CREATE INDEX IF NOT EXISTS wallet_wall_provide_55b0bf_idx
                ON wallet_wallettransaction(provider, provider_tx_id);

            CREATE INDEX IF NOT EXISTS wallet_wall_status_66d39d_idx
                ON wallet_wallettransaction(status);

            CREATE INDEX IF NOT EXISTS wallet_wallettransaction_wallet_id_idx
                ON wallet_wallettransaction(wallet_id);
            """,
            reverse_sql="",
        ),
    ]
