# ========================= apps/wallet/migrations/0003_remove_wallet_currency_wallet_is_platform_wallet_and_more.py =========================
# Generated by Django 5.2.9 on 2025-12-26 21:49

import apps.wallet.models
import django.db.models.deletion
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_create_wallettransaction_table_if_missing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="currency",
        ),
        migrations.AddField(
            model_name="wallet",
            name="is_platform_wallet",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="wallet",
            name="locked_balance",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
        ),
        migrations.AddField(
            model_name="wallet",
            name="provider",
            field=models.CharField(db_index=True, default="lumicash", max_length=30),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_transactions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=apps.wallet.models._default_initial_balance,
                max_digits=18,
            ),
        ),
        # ✅ IMPORTANT: on ne touche pas au PK de WalletTransaction (bigint)
        migrations.AlterField(
            model_name="wallettransaction",
            name="provider",
            field=models.CharField(db_index=True, default="lumicash", max_length=30),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="provider_tx_id",
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="success",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("credit", "Credit"),
                    ("debit", "Debit"),
                    ("transfer_in", "Transfer In"),
                    ("transfer_out", "Transfer Out"),
                    ("adjustment", "Adjustment"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["is_platform_wallet"], name="wallet_wall_is_plat_17a47e_idx"),
        ),
    ]
