# Generated by Django 5.2.9 on 2026-01-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_wallet_currency_wallet_is_platform_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='provider',
            field=models.CharField(choices=[('lumicash', 'Lumicash'), ('internal', 'Internal')], db_index=True, default='lumicash', max_length=30),
        ),
    ]
